### ISSUE TITLE
Make Redis optional (Bounty: 550 SOLO)

### ISSUE THREAD

**Issue by bashash** [sologenic/sologenic-xrpl-stream-js#1]
**Summary:**
In the XRPL Stream Redis is currently mandatory. We use a custom transaction management on Redis called Sologenic Transaction Management & Queue (stmxq)
https://github.com/sologenic/sologenic-xrpl-stream-js/blob/master/src/lib/stxmq.ts

** Usecase **
Since this library is designed to be used by many services, it should be optional to use Redis in the ecosystem. Managing a Redis server is sometimes expensive and resource-consuming for some users. 
Also, some clients may just want to use this system and don't worry about recovery and failovers.

**Comment by bashash** [comment]
This would require to clone stxmq.ts and make it independent from Redis (e.g map, array, etc) and allow the library just to call the correct mq based on what configuration for Redis is provided. If non-existent, then use the in-memory, if it exists then use Redis.

**Comment by okanaganrusty** [comment]
I'm working on this now.

**Comment by bashash** [comment]
merged [3a6a3c9](https://github.com/sologenic/sologenic-xrpl-stream-js/commit/39e03f52eb7be7a95fbff66938b06c36b80c903d)
