### ISSUE TITLE
Make better documentation - Including README.md (Bounty: 2000 SOLO)

### ISSUE THREAD

**Issue by bashash** [sologenic/sologenic-xrpl-stream-js#3]
**Summary**
It's important for clients to jump-start and be able to use this library. Therefore it's essential we have good documentation. 
This documentation comes from:
npm run doc "Generate HTML API documentation and open it in a browser"
npm run doc:json "Generate API documentation in typedoc JSON format"

README.md should also cover examples and a complete documentation.

**Comment by okanaganrusty** [comment]
See PR #17
